version: '2'
services:
  {% for postgres_environment in postgres_containers %}
  {% if loop.first %}# postgres{% endif %}
  {%- if postgres_environment is equalto 'live' %}
  postgres-exporter-isaac-3:
    container_name: postgres-exporter-isaac-3
    image: wrouesnel/postgres_exporter
    environment:
      - DATA_SOURCE_URI=postgres:5432/rutherford?sslmode=disable
      - DATA_SOURCE_USER=$POSTGRES_DB_USER
      - DATA_SOURCE_PASS=$POSTGRES_DB_PASSWORD

  postgres-exporter-isaac-2:
    container_name: postgres-exporter-isaac-2
    image: wrouesnel/postgres_exporter
    extra_hosts:
      - remote-postgres:$REMOTE_POSTGRES
    environment:
      - DATA_SOURCE_URI=remote-postgres:5432/rutherford?sslmode=disable
      - DATA_SOURCE_USER=$POSTGRES_DB_USER
      - DATA_SOURCE_PASS=$POSTGRES_DB_PASSWORD
  {%- else %}
  {{postgres_containers[postgres_environment].name}}-exporter:
    container_name: {{postgres_containers[postgres_environment].name}}-exporter
    image: wrouesnel/postgres_exporter
    environment:
      - DATA_SOURCE_URI={{postgres_containers[postgres_environment].name}}:5432/rutherford?sslmode=disable
      - DATA_SOURCE_USER=$POSTGRES_DB_USER
      - DATA_SOURCE_PASS=$POSTGRES_DB_PASSWORD
  {%- endif %}
  {%- endfor %}

  # elastic
  elasticsearch-exporter-isaac-3:
    container_name: elasticsearch-exporter-isaac-3
    image: justwatch/elasticsearch_exporter:1.0.2
    extra_hosts:
      - elasticsearch:$LOCAL_ELASTICSEARCH
    command:
      - '-es.uri=http://elasticsearch:9200'

  elasticsearch-exporter-isaac-2:
    container_name: elasticsearch-exporter-isaac-2
    image: justwatch/elasticsearch_exporter:1.0.2
    extra_hosts:
      - remote-elasticsearch:$REMOTE_ELASTICSEARCH
    command:
      - '-es.uri=http://remote-elasticsearch:9200'

  # metrics collating and querying
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - --storage.tsdb.retention=90d
      - --storage.tsdb.path=/prometheus/data
      - --config.file=/prometheus/prometheus.yml
    volumes:
      - ./{{prometheus_config_path}}:/etc/prometheus/prometheus.yml
      - /var/lib/prometheus:/prometheus/data

  grafana:
    container_name: grafana
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=$GRAFANA_ADMIN_USER
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASSWORD
      - GF_DATABASE_TYPE=sqlite3
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - /var/lib/grafana:/var/lib/grafana
    ports:
      - 3000:3000

networks:
  default:
    external:
      name: isaac