{%- macro prometheus_job(job_name, exporter_name, port, metrics_path='/metrics') %}
  - job_name: {{ job_name }}
    metrics_path: /metrics
    static_configs:
      - targets: [{{ exporter_name }}:{{ port }}]
{%- endmacro -%}

global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  # Isaac API
  {%- if isaac_api_containers -%}
  {%- for api_environment, container in isaac_api_containers.iteritems() -%}
  {{ prometheus_job(container.prometheus_job_name, container.exporter_name, 9966) }}
  {% endfor %}
  {%- endif %}

  # Postgres
  {%- if postgres_containers -%}
  {%- for postgres_environment, container in postgres_containers.iteritems() -%}
  {% if postgres_environment is equalto 'live' -%}
  {{ prometheus_job(container.prometheus_job_name + '_isaac_3', container.exporter_name + '-isaac-3', 9187) }}
  {{ prometheus_job(container.prometheus_job_name + '_isaac_2', container.exporter_name + '-isaac-2', 9187) }}
  {%- else %}
  {{ prometheus_job(container.prometheus_job_name, container.exporter_name, 9187) }}
  {%- endif %}
  {%- endfor %}
  {%- endif %}


  # Elastic
  {{- prometheus_job('elasticsearch_exporter_isaac_3', 'elasticsearch-exporter-isaac-3', 9200) }}
  {{ prometheus_job('elasticsearch_exporter_isaac_2', 'elasticsearch-exporter-isaac-2', 9200) }}


  # Prometheus
  {{- prometheus_job('prometheus_exporter', 'localhost', 9090) }}
