{%- macro prometheus_job(job_name, exporter_name, port, metrics_path='/metrics') %}
  - job_name: {{ job_name }}
    metrics_path: /metrics
    static_configs:
      - targets: ['{{ exporter_name }}:{{ port }}']
{%- endmacro -%}

global:
  evaluation_interval: 30s
  scrape_interval: 30s

scrape_configs:
  # Isaac API
  {% if isaac_api_containers -%}
  {%- for subject, subject_containers in isaac_api_containers.items() -%}
  # {{subject.upper()}}
  {%- for environment, environment_containers in subject_containers.items() -%}
  {%- for tag, container in environment_containers.items() -%}
  {{ prometheus_job(container.prometheus_job_name, container.exporter_name, 9966) }}
  {% endfor %}
  {%- endfor %}
  {%- endfor %}
  {%- endif %}
